// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package storage

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type track_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var TrackBinding = track_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 1009144760383425933,
}

// Track_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Track_ = struct {
	Id               *objectbox.PropertyUint64
	Uuid             *objectbox.PropertyString
	Path             *objectbox.PropertyString
	ArtistName       *objectbox.PropertyString
	SongName         *objectbox.PropertyString
	AlbumName        *objectbox.PropertyString
	AlbumTrackNumber *objectbox.PropertyInt
	TrackLength      *objectbox.PropertyInt
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &TrackBinding.Entity,
		},
	},
	Uuid: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &TrackBinding.Entity,
		},
	},
	Path: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &TrackBinding.Entity,
		},
	},
	ArtistName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &TrackBinding.Entity,
		},
	},
	SongName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &TrackBinding.Entity,
		},
	},
	AlbumName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &TrackBinding.Entity,
		},
	},
	AlbumTrackNumber: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &TrackBinding.Entity,
		},
	},
	TrackLength: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &TrackBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (track_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (track_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Track", 1, 1009144760383425933)
	model.Property("Id", 6, 1, 8328082909706324046)
	model.PropertyFlags(1)
	model.Property("Uuid", 9, 2, 1987961737853460063)
	model.PropertyFlags(4096)
	model.PropertyIndex(1, 4092924393197870388)
	model.Property("Path", 9, 3, 2074561992841698810)
	model.PropertyFlags(4096)
	model.PropertyIndex(2, 8718592668905612706)
	model.Property("ArtistName", 9, 4, 4607640011094518809)
	model.PropertyFlags(4096)
	model.PropertyIndex(3, 4058904924878660498)
	model.Property("SongName", 9, 5, 662266339228307963)
	model.PropertyFlags(4096)
	model.PropertyIndex(4, 24294085824141789)
	model.Property("AlbumName", 9, 6, 1221981067660187423)
	model.PropertyFlags(4096)
	model.PropertyIndex(5, 1169029257320798961)
	model.Property("AlbumTrackNumber", 6, 7, 756298788315811931)
	model.Property("TrackLength", 6, 8, 9108779320025497871)
	model.EntityLastPropertyId(8, 9108779320025497871)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (track_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Track).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (track_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Track).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (track_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (track_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Track)
	var offsetUuid = fbutils.CreateStringOffset(fbb, obj.Uuid)
	var offsetPath = fbutils.CreateStringOffset(fbb, obj.Path)
	var offsetArtistName = fbutils.CreateStringOffset(fbb, obj.ArtistName)
	var offsetSongName = fbutils.CreateStringOffset(fbb, obj.SongName)
	var offsetAlbumName = fbutils.CreateStringOffset(fbb, obj.AlbumName)

	// build the FlatBuffers object
	fbb.StartObject(8)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetUuid)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetPath)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetArtistName)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetSongName)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetAlbumName)
	fbutils.SetInt64Slot(fbb, 6, int64(obj.AlbumTrackNumber))
	fbutils.SetInt64Slot(fbb, 7, int64(obj.TrackLength))
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (track_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Track' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &Track{
		Id:               propId,
		Uuid:             fbutils.GetStringSlot(table, 6),
		Path:             fbutils.GetStringSlot(table, 8),
		ArtistName:       fbutils.GetStringSlot(table, 10),
		SongName:         fbutils.GetStringSlot(table, 12),
		AlbumName:        fbutils.GetStringSlot(table, 14),
		AlbumTrackNumber: fbutils.GetIntSlot(table, 16),
		TrackLength:      fbutils.GetIntSlot(table, 18),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (track_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Track, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (track_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Track), nil)
	}
	return append(slice.([]*Track), object.(*Track))
}

// Box provides CRUD access to Track objects
type TrackBox struct {
	*objectbox.Box
}

// BoxForTrack opens a box of Track objects
func BoxForTrack(ob *objectbox.ObjectBox) *TrackBox {
	return &TrackBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Track.Id property on the passed object will be assigned the new ID as well.
func (box *TrackBox) Put(object *Track) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Track.Id property on the passed object will be assigned the new ID as well.
func (box *TrackBox) Insert(object *Track) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *TrackBox) Update(object *Track) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *TrackBox) PutAsync(object *Track) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Track.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Track.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *TrackBox) PutMany(objects []*Track) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *TrackBox) Get(id uint64) (*Track, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Track), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *TrackBox) GetMany(ids ...uint64) ([]*Track, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Track), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *TrackBox) GetManyExisting(ids ...uint64) ([]*Track, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Track), nil
}

// GetAll reads all stored objects
func (box *TrackBox) GetAll() ([]*Track, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Track), nil
}

// Remove deletes a single object
func (box *TrackBox) Remove(object *Track) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *TrackBox) RemoveMany(objects ...*Track) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Track_ struct to create conditions.
// Keep the *TrackQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *TrackBox) Query(conditions ...objectbox.Condition) *TrackQuery {
	return &TrackQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Track_ struct to create conditions.
// Keep the *TrackQuery if you intend to execute the query multiple times.
func (box *TrackBox) QueryOrError(conditions ...objectbox.Condition) (*TrackQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &TrackQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See TrackAsyncBox for more information.
func (box *TrackBox) Async() *TrackAsyncBox {
	return &TrackAsyncBox{AsyncBox: box.Box.Async()}
}

// TrackAsyncBox provides asynchronous operations on Track objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type TrackAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForTrack creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use TrackBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForTrack(ob *objectbox.ObjectBox, timeoutMs uint64) *TrackAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &TrackAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *TrackAsyncBox) Put(object *Track) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *TrackAsyncBox) Insert(object *Track) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *TrackAsyncBox) Update(object *Track) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *TrackAsyncBox) Remove(object *Track) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Track which Id is either 42 or 47:
//
//	box.Query(Track_.Id.In(42, 47)).Find()
type TrackQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *TrackQuery) Find() ([]*Track, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Track), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *TrackQuery) Offset(offset uint64) *TrackQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *TrackQuery) Limit(limit uint64) *TrackQuery {
	query.Query.Limit(limit)
	return query
}

type playlist_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var PlaylistBinding = playlist_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 1182139793609600194,
}

// Playlist_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Playlist_ = struct {
	Id                *objectbox.PropertyUint64
	Uuid              *objectbox.PropertyString
	Name              *objectbox.PropertyString
	CurrentTrackId    *objectbox.PropertyUint16
	Elapsed           *objectbox.PropertyInt
	ClientIdLock      *objectbox.PropertyString
	ClientLockExpires *objectbox.PropertyInt64
	Tracks            *objectbox.RelationToMany
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &PlaylistBinding.Entity,
		},
	},
	Uuid: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &PlaylistBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &PlaylistBinding.Entity,
		},
	},
	CurrentTrackId: &objectbox.PropertyUint16{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &PlaylistBinding.Entity,
		},
	},
	Elapsed: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &PlaylistBinding.Entity,
		},
	},
	ClientIdLock: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &PlaylistBinding.Entity,
		},
	},
	ClientLockExpires: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &PlaylistBinding.Entity,
		},
	},
	Tracks: &objectbox.RelationToMany{
		Id:     1,
		Source: &PlaylistBinding.Entity,
		Target: &TrackBinding.Entity,
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (playlist_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (playlist_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Playlist", 2, 1182139793609600194)
	model.Property("Id", 6, 1, 1796519454618579982)
	model.PropertyFlags(1)
	model.Property("Uuid", 9, 2, 7106733261962919725)
	model.PropertyFlags(4096)
	model.PropertyIndex(6, 4305032471893927022)
	model.Property("Name", 9, 3, 7337893131552777598)
	model.Property("CurrentTrackId", 3, 4, 1853631187711454827)
	model.PropertyFlags(8192)
	model.Property("Elapsed", 6, 5, 1873524423846790449)
	model.Property("ClientIdLock", 9, 6, 6224481199462941621)
	model.Property("ClientLockExpires", 6, 7, 8516664682714891262)
	model.EntityLastPropertyId(7, 8516664682714891262)
	model.Relation(1, 3267482171217122691, TrackBinding.Id, TrackBinding.Uid)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (playlist_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Playlist).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (playlist_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Playlist).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (playlist_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	if err := BoxForPlaylist(ob).RelationReplace(Playlist_.Tracks, id, object, object.(*Playlist).Tracks); err != nil {
		return err
	}

	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (playlist_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Playlist)
	var offsetUuid = fbutils.CreateStringOffset(fbb, obj.Uuid)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetClientIdLock = fbutils.CreateStringOffset(fbb, obj.ClientIdLock)

	// build the FlatBuffers object
	fbb.StartObject(7)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetUuid)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetName)
	fbutils.SetUint16Slot(fbb, 3, obj.CurrentTrackId)
	fbutils.SetInt64Slot(fbb, 4, int64(obj.Elapsed))
	fbutils.SetUOffsetTSlot(fbb, 5, offsetClientIdLock)
	fbutils.SetInt64Slot(fbb, 6, obj.ClientLockExpires)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (playlist_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Playlist' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	var relTracks []*Track
	if rIds, err := BoxForPlaylist(ob).RelationIds(Playlist_.Tracks, propId); err != nil {
		return nil, err
	} else if rSlice, err := BoxForTrack(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relTracks = rSlice
	}

	return &Playlist{
		Id:                propId,
		Uuid:              fbutils.GetStringSlot(table, 6),
		Name:              fbutils.GetStringSlot(table, 8),
		CurrentTrackId:    fbutils.GetUint16Slot(table, 10),
		Elapsed:           fbutils.GetIntSlot(table, 12),
		Tracks:            relTracks,
		ClientIdLock:      fbutils.GetStringSlot(table, 14),
		ClientLockExpires: fbutils.GetInt64Slot(table, 16),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (playlist_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Playlist, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (playlist_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Playlist), nil)
	}
	return append(slice.([]*Playlist), object.(*Playlist))
}

// Box provides CRUD access to Playlist objects
type PlaylistBox struct {
	*objectbox.Box
}

// BoxForPlaylist opens a box of Playlist objects
func BoxForPlaylist(ob *objectbox.ObjectBox) *PlaylistBox {
	return &PlaylistBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Playlist.Id property on the passed object will be assigned the new ID as well.
func (box *PlaylistBox) Put(object *Playlist) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Playlist.Id property on the passed object will be assigned the new ID as well.
func (box *PlaylistBox) Insert(object *Playlist) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *PlaylistBox) Update(object *Playlist) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *PlaylistBox) PutAsync(object *Playlist) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Playlist.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Playlist.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *PlaylistBox) PutMany(objects []*Playlist) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *PlaylistBox) Get(id uint64) (*Playlist, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Playlist), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *PlaylistBox) GetMany(ids ...uint64) ([]*Playlist, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Playlist), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *PlaylistBox) GetManyExisting(ids ...uint64) ([]*Playlist, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Playlist), nil
}

// GetAll reads all stored objects
func (box *PlaylistBox) GetAll() ([]*Playlist, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Playlist), nil
}

// Remove deletes a single object
func (box *PlaylistBox) Remove(object *Playlist) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *PlaylistBox) RemoveMany(objects ...*Playlist) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Playlist_ struct to create conditions.
// Keep the *PlaylistQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *PlaylistBox) Query(conditions ...objectbox.Condition) *PlaylistQuery {
	return &PlaylistQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Playlist_ struct to create conditions.
// Keep the *PlaylistQuery if you intend to execute the query multiple times.
func (box *PlaylistBox) QueryOrError(conditions ...objectbox.Condition) (*PlaylistQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &PlaylistQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See PlaylistAsyncBox for more information.
func (box *PlaylistBox) Async() *PlaylistAsyncBox {
	return &PlaylistAsyncBox{AsyncBox: box.Box.Async()}
}

// PlaylistAsyncBox provides asynchronous operations on Playlist objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type PlaylistAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForPlaylist creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use PlaylistBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForPlaylist(ob *objectbox.ObjectBox, timeoutMs uint64) *PlaylistAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &PlaylistAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *PlaylistAsyncBox) Put(object *Playlist) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *PlaylistAsyncBox) Insert(object *Playlist) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *PlaylistAsyncBox) Update(object *Playlist) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *PlaylistAsyncBox) Remove(object *Playlist) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Playlist which Id is either 42 or 47:
//
//	box.Query(Playlist_.Id.In(42, 47)).Find()
type PlaylistQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *PlaylistQuery) Find() ([]*Playlist, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Playlist), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *PlaylistQuery) Offset(offset uint64) *PlaylistQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *PlaylistQuery) Limit(limit uint64) *PlaylistQuery {
	query.Query.Limit(limit)
	return query
}

type friend_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var FriendBinding = friend_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 6526345522080463439,
}

// Friend_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Friend_ = struct {
	Id       *objectbox.PropertyUint64
	friendId *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &FriendBinding.Entity,
		},
	},
	friendId: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &FriendBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (friend_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (friend_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Friend", 3, 6526345522080463439)
	model.Property("Id", 6, 1, 883542943098408523)
	model.PropertyFlags(1)
	model.Property("friendId", 9, 2, 6453426738975360861)
	model.PropertyFlags(4096)
	model.PropertyIndex(7, 8254895745365351782)
	model.EntityLastPropertyId(2, 6453426738975360861)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (friend_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Friend).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (friend_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Friend).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (friend_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (friend_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Friend)
	var offsetfriendId = fbutils.CreateStringOffset(fbb, obj.friendId)

	// build the FlatBuffers object
	fbb.StartObject(2)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetfriendId)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (friend_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Friend' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &Friend{
		Id:       propId,
		friendId: fbutils.GetStringSlot(table, 6),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (friend_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Friend, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (friend_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Friend), nil)
	}
	return append(slice.([]*Friend), object.(*Friend))
}

// Box provides CRUD access to Friend objects
type FriendBox struct {
	*objectbox.Box
}

// BoxForFriend opens a box of Friend objects
func BoxForFriend(ob *objectbox.ObjectBox) *FriendBox {
	return &FriendBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Friend.Id property on the passed object will be assigned the new ID as well.
func (box *FriendBox) Put(object *Friend) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Friend.Id property on the passed object will be assigned the new ID as well.
func (box *FriendBox) Insert(object *Friend) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *FriendBox) Update(object *Friend) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *FriendBox) PutAsync(object *Friend) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Friend.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Friend.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *FriendBox) PutMany(objects []*Friend) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *FriendBox) Get(id uint64) (*Friend, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Friend), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *FriendBox) GetMany(ids ...uint64) ([]*Friend, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Friend), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *FriendBox) GetManyExisting(ids ...uint64) ([]*Friend, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Friend), nil
}

// GetAll reads all stored objects
func (box *FriendBox) GetAll() ([]*Friend, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Friend), nil
}

// Remove deletes a single object
func (box *FriendBox) Remove(object *Friend) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *FriendBox) RemoveMany(objects ...*Friend) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Friend_ struct to create conditions.
// Keep the *FriendQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *FriendBox) Query(conditions ...objectbox.Condition) *FriendQuery {
	return &FriendQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Friend_ struct to create conditions.
// Keep the *FriendQuery if you intend to execute the query multiple times.
func (box *FriendBox) QueryOrError(conditions ...objectbox.Condition) (*FriendQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &FriendQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See FriendAsyncBox for more information.
func (box *FriendBox) Async() *FriendAsyncBox {
	return &FriendAsyncBox{AsyncBox: box.Box.Async()}
}

// FriendAsyncBox provides asynchronous operations on Friend objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type FriendAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForFriend creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use FriendBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForFriend(ob *objectbox.ObjectBox, timeoutMs uint64) *FriendAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &FriendAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *FriendAsyncBox) Put(object *Friend) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *FriendAsyncBox) Insert(object *Friend) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *FriendAsyncBox) Update(object *Friend) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *FriendAsyncBox) Remove(object *Friend) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Friend which Id is either 42 or 47:
//
//	box.Query(Friend_.Id.In(42, 47)).Find()
type FriendQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *FriendQuery) Find() ([]*Friend, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Friend), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *FriendQuery) Offset(offset uint64) *FriendQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *FriendQuery) Limit(limit uint64) *FriendQuery {
	query.Query.Limit(limit)
	return query
}

type user_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var UserBinding = user_EntityInfo{
	Entity: objectbox.Entity{
		Id: 4,
	},
	Uid: 4728390412674560454,
}

// User_ contains type-based Property helpers to facilitate some common operations such as Queries.
var User_ = struct {
	Id           *objectbox.PropertyUint64
	Uuid         *objectbox.PropertyString
	FirstName    *objectbox.PropertyString
	LastName     *objectbox.PropertyString
	EmailAddress *objectbox.PropertyString
	Password     *objectbox.PropertyString
	Enabled      *objectbox.PropertyBool
	AdminUser    *objectbox.PropertyBool
	LastPlaylist *objectbox.PropertyUint64
	Tracks       *objectbox.RelationToMany
	Playlists    *objectbox.RelationToMany
	Friends      *objectbox.RelationToMany
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &UserBinding.Entity,
		},
	},
	Uuid: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &UserBinding.Entity,
		},
	},
	FirstName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &UserBinding.Entity,
		},
	},
	LastName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &UserBinding.Entity,
		},
	},
	EmailAddress: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &UserBinding.Entity,
		},
	},
	Password: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &UserBinding.Entity,
		},
	},
	Enabled: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &UserBinding.Entity,
		},
	},
	AdminUser: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &UserBinding.Entity,
		},
	},
	LastPlaylist: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &UserBinding.Entity,
		},
	},
	Tracks: &objectbox.RelationToMany{
		Id:     2,
		Source: &UserBinding.Entity,
		Target: &TrackBinding.Entity,
	},
	Playlists: &objectbox.RelationToMany{
		Id:     3,
		Source: &UserBinding.Entity,
		Target: &PlaylistBinding.Entity,
	},
	Friends: &objectbox.RelationToMany{
		Id:     4,
		Source: &UserBinding.Entity,
		Target: &FriendBinding.Entity,
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (user_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (user_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("User", 4, 4728390412674560454)
	model.Property("Id", 6, 1, 4588827918934279293)
	model.PropertyFlags(1)
	model.Property("Uuid", 9, 2, 5843302712282538112)
	model.PropertyFlags(4096)
	model.PropertyIndex(8, 4804161878894786730)
	model.Property("FirstName", 9, 3, 7789964683614264008)
	model.Property("LastName", 9, 4, 6952393024719262183)
	model.Property("EmailAddress", 9, 5, 7450737382308600686)
	model.PropertyFlags(4096)
	model.PropertyIndex(9, 2872564972079443293)
	model.Property("Password", 9, 6, 729577253119581218)
	model.Property("Enabled", 1, 7, 1652173814307647868)
	model.Property("AdminUser", 1, 8, 6739946297492405455)
	model.Property("LastPlaylist", 6, 9, 386897330895652911)
	model.PropertyFlags(8192)
	model.EntityLastPropertyId(9, 386897330895652911)
	model.Relation(2, 8897016110600791681, TrackBinding.Id, TrackBinding.Uid)
	model.Relation(3, 5520690084346431236, PlaylistBinding.Id, PlaylistBinding.Uid)
	model.Relation(4, 4712361723987089641, FriendBinding.Id, FriendBinding.Uid)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (user_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*User).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (user_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*User).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (user_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	if err := BoxForUser(ob).RelationReplace(User_.Tracks, id, object, object.(*User).Tracks); err != nil {
		return err
	}

	if err := BoxForUser(ob).RelationReplace(User_.Playlists, id, object, object.(*User).Playlists); err != nil {
		return err
	}

	if err := BoxForUser(ob).RelationReplace(User_.Friends, id, object, object.(*User).Friends); err != nil {
		return err
	}

	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (user_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*User)
	var offsetUuid = fbutils.CreateStringOffset(fbb, obj.Uuid)
	var offsetFirstName = fbutils.CreateStringOffset(fbb, obj.FirstName)
	var offsetLastName = fbutils.CreateStringOffset(fbb, obj.LastName)
	var offsetEmailAddress = fbutils.CreateStringOffset(fbb, obj.EmailAddress)
	var offsetPassword = fbutils.CreateStringOffset(fbb, obj.Password)

	// build the FlatBuffers object
	fbb.StartObject(9)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetUuid)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetFirstName)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetLastName)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetEmailAddress)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetPassword)
	fbutils.SetBoolSlot(fbb, 6, obj.Enabled)
	fbutils.SetBoolSlot(fbb, 7, obj.AdminUser)
	fbutils.SetUint64Slot(fbb, 8, obj.LastPlaylist)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (user_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'User' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	var relTracks []*Track
	if rIds, err := BoxForUser(ob).RelationIds(User_.Tracks, propId); err != nil {
		return nil, err
	} else if rSlice, err := BoxForTrack(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relTracks = rSlice
	}

	var relPlaylists []*Playlist
	if rIds, err := BoxForUser(ob).RelationIds(User_.Playlists, propId); err != nil {
		return nil, err
	} else if rSlice, err := BoxForPlaylist(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relPlaylists = rSlice
	}

	var relFriends []*Friend
	if rIds, err := BoxForUser(ob).RelationIds(User_.Friends, propId); err != nil {
		return nil, err
	} else if rSlice, err := BoxForFriend(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relFriends = rSlice
	}

	return &User{
		Id:           propId,
		Uuid:         fbutils.GetStringSlot(table, 6),
		FirstName:    fbutils.GetStringSlot(table, 8),
		LastName:     fbutils.GetStringSlot(table, 10),
		EmailAddress: fbutils.GetStringSlot(table, 12),
		Password:     fbutils.GetStringSlot(table, 14),
		Enabled:      fbutils.GetBoolSlot(table, 16),
		AdminUser:    fbutils.GetBoolSlot(table, 18),
		LastPlaylist: fbutils.GetUint64Slot(table, 20),
		Tracks:       relTracks,
		Playlists:    relPlaylists,
		Friends:      relFriends,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (user_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*User, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (user_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*User), nil)
	}
	return append(slice.([]*User), object.(*User))
}

// Box provides CRUD access to User objects
type UserBox struct {
	*objectbox.Box
}

// BoxForUser opens a box of User objects
func BoxForUser(ob *objectbox.ObjectBox) *UserBox {
	return &UserBox{
		Box: ob.InternalBox(4),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the User.Id property on the passed object will be assigned the new ID as well.
func (box *UserBox) Put(object *User) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the User.Id property on the passed object will be assigned the new ID as well.
func (box *UserBox) Insert(object *User) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *UserBox) Update(object *User) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *UserBox) PutAsync(object *User) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the User.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the User.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *UserBox) PutMany(objects []*User) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *UserBox) Get(id uint64) (*User, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*User), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *UserBox) GetMany(ids ...uint64) ([]*User, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*User), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *UserBox) GetManyExisting(ids ...uint64) ([]*User, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*User), nil
}

// GetAll reads all stored objects
func (box *UserBox) GetAll() ([]*User, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*User), nil
}

// Remove deletes a single object
func (box *UserBox) Remove(object *User) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *UserBox) RemoveMany(objects ...*User) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the User_ struct to create conditions.
// Keep the *UserQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *UserBox) Query(conditions ...objectbox.Condition) *UserQuery {
	return &UserQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the User_ struct to create conditions.
// Keep the *UserQuery if you intend to execute the query multiple times.
func (box *UserBox) QueryOrError(conditions ...objectbox.Condition) (*UserQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &UserQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See UserAsyncBox for more information.
func (box *UserBox) Async() *UserAsyncBox {
	return &UserAsyncBox{AsyncBox: box.Box.Async()}
}

// UserAsyncBox provides asynchronous operations on User objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type UserAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForUser creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use UserBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForUser(ob *objectbox.ObjectBox, timeoutMs uint64) *UserAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 4, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 4: %s" + err.Error())
	}
	return &UserAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *UserAsyncBox) Put(object *User) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *UserAsyncBox) Insert(object *User) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *UserAsyncBox) Update(object *User) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *UserAsyncBox) Remove(object *User) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all User which Id is either 42 or 47:
//
//	box.Query(User_.Id.In(42, 47)).Find()
type UserQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *UserQuery) Find() ([]*User, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*User), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *UserQuery) Offset(offset uint64) *UserQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *UserQuery) Limit(limit uint64) *UserQuery {
	query.Query.Limit(limit)
	return query
}
