// Code generated by ObjectBox; DO NOT EDIT.

package storage

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(TrackBinding)
	model.RegisterBinding(PlaylistBinding)
	model.RegisterBinding(FriendBinding)
	model.RegisterBinding(UserBinding)
	model.LastEntityId(4, 4728390412674560454)
	model.LastIndexId(9, 2872564972079443293)
	model.LastRelationId(4, 4712361723987089641)

	return model
}
